version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    branches:
      ignore: deploy
    steps:
      - restore_cache:
          # Restore a basic .git to prevent needing to download the whole thing.
          keys:
            - git-cimg-python3.8-{{ .Branch }}
            - git-cimg-python3.8
      - checkout
      - save_cache:
          key: git-cimg-python3.8-{{ .Branch }}
          paths:
            - ".git"
      - restore_cache:
          key: env-cimg-python3.8-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python dependencies in venv
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            python3 -m venv env
            env/bin/pip3 install -r requirements.txt --upgrade
            env/bin/pip3 install -r user_requirements.txt --upgrade
      - save_cache:
          key: env-cimg-python3.8-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Lint tests
          command: env/bin/python3 -m flake8 --config=tox_tests.ini ./test/
      - run:
          name: Lint classes
          command: env/bin/python3 -m flake8 --config=tox_classes.ini ./classes/
      - run:
          name: Lint code
          command: env/bin/python3 -m flake8 ./
      - run:
          name: Prepare Git for test
          command: |
            git config user.name SmokeDetector
            git config user.email "smokey@erwaysoftware.com"
      - run:
          name: cat users.yml
          command: cat users.yml
      - run:
          name: cat test/data_test_spamhandling.txt
          command: cat test/data_test_spamhandling.txt
      - run:
          name: Pytest
          # Use 5 processes is intended to allow one DNS lookup bound long running test run
          # in parallel with most of the other tests which generally consume more CPU.
          command: env/bin/python3 -W default::Warning -m pytest -n 17 --dist loadgroup test
