name: build

on:
  push:
    branches-ignore:
      - deploy
  pull_request:
    branches-ignore:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.10'
    steps:
    - uses: actions/checkout@v3
    - name: Fetch branches
      run: |
        git remote set-branches --add origin deploy
        git fetch --depth=5 origin master deploy
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup cache
      id: cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-cache-version-1-${{ hashFiles('**/requirements.txt') }}}-${{ hashFiles('**/user_requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.pythonLocation }}-pip-cache-version-1-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/user_requirements.txt') }}
          ${{ runner.os }}-${{ env.pythonLocation }}-pip-cache-version-1-
        path: |
          ~/.cache/pip
    - name: Install Python dependencies
      run: |
        pip3 install -U wheel --upgrade-strategy eager
        pip3 install -U -r requirements.txt -r user_requirements.txt pytest-cov coveralls --upgrade-strategy eager
    - name: Pytest
      run: |
        python3 -W default::Warning -m pytest \
          -n 11 \
          --dist loadgroup \
          test/test_regex.py
