name: build

on:
  push:
    branches-ignore:
      - deploy
  pull_request:
    branches-ignore:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Fetch branches
      run: |
        git remote set-branches --add origin deploy
        for i in $(seq 1 5); do [ $i -gt 1 ] && sleep 5; git fetch --depth=5 origin master deploy && s=0 && break || s=$?; done; (exit $s)
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-1-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-1-
    - name: Install dependencies
      run: |
        for i in $(seq 1 5); do [ $i -gt 1 ] && sleep 5; pip3 install "pip==21.1.3" && s=0 && break || s=$?; done; (exit $s)
        pip3 --version
        for i in $(seq 1 5); do [ $i -gt 1 ] && sleep 5; pip3 install -U wheel && s=0 && break || s=$?; done; (exit $s)
        for i in $(seq 1 5); do [ $i -gt 1 ] && sleep 5; pip3 install -U -r requirements.txt -r user_requirements.txt pytest-cov coveralls && s=0 && break || s=$?; done; (exit $s)
    - name: Lint tests
      run: flake8 --config=tox_tests.ini test/
    - name: Lint classes
      run: flake8 --config=tox_classes.ini classes/
    - name: Lint code
      run: flake8 ./
    - name: Pytest
      run: |
        python3 -W default::Warning -m pytest \
          --cov=chatcommunicate \
          --cov=findspam \
          --cov=globalvars \
          --cov=spamhandling \
          --cov=datahandling \
          --cov=chatcommands \
          --cov=helpers \
          test
